version: "2"
services:
  backend:
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    image: keys_backend:dev
    ports:
      - 4000:4000
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
  frontend:
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    image: keys_frontend:dev
    ports:
      - 3001:3000
    volumes:
      - ./frontend:/usr/src/app
  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_DB: keys
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database/postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  db_test:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_DB: keys
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database/postgres-data-test:/var/lib/postgresql/data
  gamma_backend:
    image: cthit/gamma-backend
    environment:
      DB_HOST: gamma_db
      SERVER_PORT: 8081
      FRONTEND_CLIENT_ID: 7hAdUEtMo4MgFnA7ZoZ41ohTe1NNRoJmjL67Gf0NIrrBnauyhc
      FRONTEND_CLIENT_SECRET: secret
      FRONTEND_REDIRECT_URI: http://localhost:3000/login
      SUCCESSFUL_LOGIN: http://localhost:3000
      DEFAULT_CLIENT_NAME: name
      DEFAULT_CLIENT_ID: id
      DEFAULT_CLIENT_SECRET: secret
      DEFAULT_REDIRECT_URI: http://localhost:3001/auth/account/callback
      DEFAULT_API_KEY: key
      CORS_ALLOWED_ORIGIN: "*"
    ports:
      - 8081:8081
    depends_on:
      - gamma_db
  gamma_frontend:
    image: cthit/gamma-frontend:development
    environment:
      REACT_APP_BACKEND_URL: http://localhost:8081/api
      REACT_APP_FRONTEND_URL: http://localhost:3000
    ports:
      - 3000:3000
  gamma_db:
    image: postgres:10
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    restart: always